version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,dynamodb,cloudformation,lambda,stepfunctions,s3
    ports:
      - '4566:4566'
      - '4571:4571'
