service: infra-project

provider:
  name: aws
  region: us-east-1
  stackName: company-profiler-infra
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:us-east-1:*:table/company-profiler-table"
        - Effect: Allow
          Action:
            - sqs:*
          Resource:
            - "arn:aws:sqs:us-east-1:*:information-getter-queue"
            - "arn:aws:sqs:us-east-1:*:scraping-ready-queue"
        - Effect: Allow
          Action:
            - sns:*
          Resource: "arn:aws:sns:us-east-1:*:scraping-ready-topic"

plugins:
  - serverless-offline

resources:
  Resources:
    scrapingReadyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: scraping-ready-queue
    informationGetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: information-getter-queue
    companyProfilerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: company-profiler-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    scrapingReadyTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: scraping-ready-topic
